version: '3.6'
services: 
  postgres:
    image: postgres
    restart: always
    environment: 
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=exploro

    ports: 
      - "5440:5432"
    volumes: 
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    
  pgadmin-compose:
    image: dpage/pgadmin4
    environment: 
      PGADMIN_DEFAULT_EMAIL: "test@test.com"
      PGADMIN_DEFAULT_PASSWORD: "test"
    ports: 
      - "16543:80"
    depends_on: 
      - postgres
  
  # jake:
  #   image: jake
  #   restart: always
  #   ports:
  #     - "8081:8080"
  #   depends_on:
  #     - postgres
  #   env_file:
  #     - .env
