CREATE TABLE api_key (
  id SERIAL PRIMARY KEY,
  key TEXT NOT NULL UNIQUE,
  security_level SMALLINT NOT NULL,
  name TEXT NOT NULL UNIQUE,
  created TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  edited TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

INSERT INTO api_key (key, security_level, name) VALUES ('e8eafe91-781e-4d5b-a615-807540518b24', 1, 'admin');
