CREATE TABLE country (
  id SERIAL PRIMARY KEY,
  name varchar(200) UNIQUE NOT NULL,
  slug varchar(250) UNIQUE NOT NULL,
  description_long TEXT NOT NULL,
  description_short TEXT NOT NULL,
  image_link TEXT NOT NULL,
  thumbnail_link TEXT NOT NULL,
  special_offer_image_link TEXT,
  video_link TEXT,
  gallery TEXT[] NOT NULL,
  featured_country FLOAT,
  continent integer references continent(id) NOT NULL DEFAULT 1,
  tags TEXT,
  created TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  edited TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TRIGGER trigger_row_edit_update_timestamp_for_country
BEFORE UPDATE ON country
FOR EACH ROW
EXECUTE FUNCTION update_updated_on();

-- Insert for Country
INSERT INTO country (name, slug, description_long, description_short, image_link, thumbnail_link, gallery, created, edited) VALUES ('MISSING DATA', 'missing-data', 'Long description for MISSING DATA', 'Short description for MISSING DATA', 'image_link_here', 'thumbnail_link_here', ARRAY['gallery1', 'gallery2'], CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
       -- ('United Arab Emirates', 'united-arab-emirates', 'Long description for United Arab Emirates', 'Short description for United Arab Emirates', 'image_link_here', 'thumbnail_link_here', ARRAY['gallery1', 'gallery2'], CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       -- ('Netherlands', 'netherlands', 'Long description for Netherlands', 'Short description for Netherlands', 'image_link_here', 'thumbnail_link_here', ARRAY['gallery1', 'gallery2'], CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       -- ('France', 'france', 'Long description for France', 'Short description for France', 'image_link_here', 'thumbnail_link_here', ARRAY['gallery1', 'gallery2'], CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       -- ('South Africa', 'south-africa', 'Long description for South Africa', 'Short description for South Africa', 'image_link_here', 'thumbnail_link_here', ARRAY['gallery1', 'gallery2'], CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       -- ('United States', 'united-states', 'Long description for United States', 'Short description for United States', 'image_link_here', 'thumbnail_link_here', ARRAY['gallery1', 'gallery2'], CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       -- ('Thailand', 'thailand', 'Long description for Thailand', 'Short description for Thailand', 'image_link_here', 'thumbnail_link_here', ARRAY['gallery1', 'gallery2'], CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       -- ('Australia', 'australia', 'Long description for Australia', 'Short description for Australia', 'image_link_here', 'thumbnail_link_here', ARRAY['gallery1', 'gallery2'], CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       -- ('India', 'india', 'Long description for India', 'Short description for India', 'image_link_here', 'thumbnail_link_here', ARRAY['gallery1', 'gallery2'], CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       -- ('Jamaica', 'jamaica', 'Long description for Jamaica', 'Short description for Jamaica', 'image_link_here', 'thumbnail_link_here', ARRAY['gallery1', 'gallery2'], CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       -- ('United Kingdom', 'united-kingdom', 'Long description for United Kingdom', 'Short description for United Kingdom', 'image_link_here', 'thumbnail_link_here', ARRAY['gallery1', 'gallery2'], CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       -- ('Vietnam', 'vietnam', 'Long description for Vietnam', 'Short description for Vietnam', 'image_link_here', 'thumbnail_link_here', ARRAY['gallery1', 'gallery2'], CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       -- ('Malaysia', 'malaysia', 'Long description for Malaysia', 'Short description for Malaysia', 'image_link_here', 'thumbnail_link_here', ARRAY['gallery1', 'gallery2'], CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       -- ('Norway', 'norway', 'Long description for Norway', 'Short description for Norway', 'image_link_here', 'thumbnail_link_here', ARRAY['gallery1', 'gallery2'], CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO country (name, slug, description_long, description_short, image_link, thumbnail_link, special_offer_image_link, video_link, gallery, featured_country, continent) VALUES ('United Arab Emirates', 'united-arab-emirates', 'The UAE is on the coastlines of the Persian Gulf and the Gulf of Oman. The country is not large, covering an area of 83,600 kilometers, slightly smaller than the American state of Maine. However, it is significant in influence and seen as the financial center of the Middle East. It is a country rich in culture and history, and houses many of the world’s oil supplies. Today, many travelers find it a convenient starting point for travels in the Middle East. The UAE was unlikely to be on anybody’s tourist itinerary for millennia. However, the discovery of oil and natural gas changed all that, conveniently coinciding with a generally relaxed version of Islam, at least for wealthy foreigners. The country is famous for its many mega-projects, including artificial islands, the world’s tallest buildings, and massive shopping malls offering every product you can think of, catering to those with deep pockets. You will find incredible nightlife, excellent restaurants, and the newest vehicles cruising up and down the street. The less known side of the UAE includes remote, magnificent deserts with massive dunes reaching into the sky and jagged mountains in the northeast emirates bordering Oman.', 'The country is famous for its many mega-projects, including artificial islands, the world’s tallest buildings, and massive shopping malls offering every product you can think of, catering to those with deep pockets.', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63be4c22bd2de3c2d77d28e5_Dubai-Footer-Thumbnail_11_0_6.jpg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63be4c22bd2de3c2d77d28e5_Dubai-Footer-Thumbnail_11_0_6.jpg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c6f3ea94d66b7dc5c199ec_63be46e3508ab6f2c169d78e_2ec6dbebf77fe703dc92d325b6d7b461.png', 'https://www.imdb.com/', ARRAY[''], 1, 2);


INSERT INTO country (name, slug, description_long, description_short, image_link, thumbnail_link, special_offer_image_link, video_link, gallery, featured_country, continent) VALUES ('Netherlands', 'netherlands', 'Amsterdam is the capital of the Netherlands, and is known for its art history, elaborate canal system, houses with gabled windows and legacy of the city’s 17th century golden age. The city is famous for its museums, especially the world famous Van Gogh Museum. Amsterdam is not only the seat of government in the Netherlands, but also the commercial capital of the country. The metropolitan Amsterdam population was 1.5 million in 2019. The city is built on land reclaimed from the North Sea, and much of the city is below sea level, with much of the city is accessed by canal. This unique character has earned Amsterdam the nick name ‘the Venice of the North.’ Because of the uniqueness of Amsterdam, the UN has designated the city as a World Heritage site.', 'Amsterdam is not only the seat of government in the Netherlands, but also the commercial capital of the country.', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c24dae243adcc2730870a0_amsterdam-banner.jpg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63be4b34d526b7e1f7c8e1dc_Amsterdam-Footer-Thumbnail_13_4_5.jpg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63be4b34d526b7e1f7c8e1dc_Amsterdam-Footer-Thumbnail_13_4_5.jpg', 'https://demo.exploro.com/3rdparty/gde/videos/Netherlands%20-%2045%20sec%20Hero%20Video%20.mp4', ARRAY[''], 1, 3);


INSERT INTO country (name, slug, description_long, description_short, image_link, thumbnail_link, special_offer_image_link, video_link, gallery, featured_country, continent) VALUES ('France', 'france', 'France is one of the most famous countries in all of the world. Many people, especially from western countries, dream about visiting France. Travelers are drawn here by the countless cafés, ancient villages, and world-famous culinary. France is a country that has given the world many of its great philosophers, writers, artists, and scientists. France is also a beautiful country with unique geographical diversity from its long coastlines, massive mountain ranges, and breathtaking farmland vistas. France has been the world’s most-visited country for over twenty years, and for good reason. The country is considered to be the very cultural capital of the world, with some of the best foods and a relish for romance. People come from all around to enjoy all France has to offer. It received 89 million visitors in 2018. France is home to dozens of major tourist attractions, including Europe’s most popular Disneyland Paris and the Eiffel tower. Enjoy the one-of-a-kind experience of visiting France.', '', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4ba91c3e3751ff240f5_france-banner.jpeg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4ba91c3e31b95f240f6_france-banner.jpeg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4b73c6fd615560a96b5_63c6f3ea94d66b7dc5c199ec_63be46e3508ab6f2c169d78e_2ec6dbebf77fe703dc92d325b6d7b461.png', '', ARRAY[''], 2, 3);


INSERT INTO country (name, slug, description_long, description_short, image_link, thumbnail_link, special_offer_image_link, video_link, gallery, featured_country) VALUES ('South Africa', 'south-africa', 'South Africa is a large country with a rich and diverse history. One of the main attractions of South Africa is the unique fact of it being a biodiversity hotspot. There is a large diversity of unique biomes, plant and animal life, and a multi-ethnic society representing many cultures, languages, and religions. South African cuisine is highly diverse, with many delicious foods from different cultures and regions. In the rural areas, the cultural traditions survive most strongly, and remnants survive in the city, showing through clothing and culture. South Africa has some of the oldest art in all of the world. In a large South African cave, you can find art that dates back to 75,000 years ago! The tribes of the Khoisan peoples moving into South Africa around 10,000 BC have their fluent art styles seen today in many cave paintings.', '', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4bc70feea6b0a3cf3db_south-africa-banner.jpeg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4bc70feeab0b73cf3dc_south-africa-banner.jpeg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4b73c6fd615560a96b5_63c6f3ea94d66b7dc5c199ec_63be46e3508ab6f2c169d78e_2ec6dbebf77fe703dc92d325b6d7b461.png', '', ARRAY[''], 2);


INSERT INTO country (name, slug, description_long, description_short, image_link, thumbnail_link, special_offer_image_link, video_link, gallery, featured_country, continent) VALUES ('United States', 'united-states', 'The United States of America places a high level of importance on international measures of economic freedom, quality of life, higher education, and human rights. It is home to many cultures and a wide variety of ethnic groups, traditions, and values. The United States offers sixty-nine national parks and hundreds of other federally managed parks, forests, and wilderness areas that provide unlimited opportunities for outdoor enthusiasts. The beaches are beautiful, and the mountains are majestic. The United States is known for its attractions, including the Grand Canyon, Yellowstone Park, Denali''s Peak, the Oregon Coast, and the Florida Everglades. The food opportunities are endless, with some of the best restaurants in North America. The United States is full of prosperity and a can-do attitude. This beautiful melting pot offers many great things!', 'The United States is known for its attractions, including the Grand Canyon, Yellowstone Park, Denali''s Peak, the Oregon Coast, and the Florida Everglades.', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c86a0d35c4b590b224c5b6_banner_8.jpg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c4c0e995a3b818477b9c62_Country-USA-Thumbnail.jpg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c6f3ea94d66b7dc5c199ec_63be46e3508ab6f2c169d78e_2ec6dbebf77fe703dc92d325b6d7b461.png', 'https://spirit.exploro.com/3rdparty/gde/videos/usa_0.mp4', ARRAY[''], 1, 4);


INSERT INTO country (name, slug, description_long, description_short, image_link, thumbnail_link, special_offer_image_link, video_link, gallery, featured_country, continent) VALUES ('Thailand', 'thailand', 'Bangkok is the capital and largest city in Thailand and is known for its ornate temples and its vibrant street life. Many citizens travel using the Chao Phraya River and the multitude of canals that run through the city. Tourists flock to the Rattanakosin Royal District which is home to the opulent Grand Palace and its sacred Wat Phra Kaew Temple with its famous statue of a reclining Buddha.', 'Bangkok is the capital and largest city in Thailand and is known for its ornate temples and its vibrant street life.', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c24ca1942827691ad0e46f_bangkok-banner-main.jpg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63be4bf4044ddccc4a0b6396_Bangkok-Thumbnail_4_0_5.jpg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c6f3ea94d66b7dc5c199ec_63be46e3508ab6f2c169d78e_2ec6dbebf77fe703dc92d325b6d7b461.png', 'https://demo.exploro.com/3rdparty/gde/videos/Bangkok%20City%20Hero%20-%20No%20Titles.mp4', ARRAY[''], 1, 5);


INSERT INTO country (name, slug, description_long, description_short, image_link, thumbnail_link, special_offer_image_link, video_link, gallery, featured_country, continent) VALUES ('Australia', 'australia', 'Indigenous peoples lived in the Melbourne area up to 40,000 years before the first British settlers arrived in the 19th century when Melbourne was officially founded in 1835. Settlers from Tasmania "purchased" land from the local Aboriginal people.', 'Indigenous peoples lived in the Melbourne area up to 40,000 years before the first British settlers arrived in the 19th century when Melbourne was officially founded in 1835. Settlers from Tasmania "purchased" land from the local Aboriginal people.', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c996fc7b6ea9d19de0bd81_63c8d0a025c836545ae48d76_1920x1080-Melbourne-1_0-p-1080.jpg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c996fc7b6ea9d19de0bd81_63c8d0a025c836545ae48d76_1920x1080-Melbourne-1_0-p-1080.jpg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c9971a14afcf29e6e66a0b_63be46e3508ab6f2c169d78e_2ec6dbebf77fe703dc92d325b6d7b461.png', '', ARRAY[''], 1, 7);


INSERT INTO country (name, slug, description_long, description_short, image_link, thumbnail_link, special_offer_image_link, video_link, gallery, featured_country, continent) VALUES ('India', 'india', 'Delhi is considered one of the largest cities in the world. It is also the capital of India. Different peoples have inhabited the city since the 6th century BC. Throughout this history, Delhi served as the capital of various kingdoms and empires, most notably the Tomars, Chahamanas, Delhi Sultanate, and Mughals. For hundreds of years, Delhi has been a dominant trading and commercial center in northern India. It has grown as an important corporate and finance center since the 1990s. Delhi has a beautiful natural landscape with greenery in all directions. Take a walk through one of the many gardens or a leisurely hike in the park. You will love the intriguing monuments, culture, performing art venues, and excellent cuisines.', 'Delhi served as the capital of various kingdoms and empires, most notably the Tomars, Chahamanas, Delhi Sultanate, and Mughals.', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c24d3a942827788cd0efd7_delhi-banner_0.jpg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63be4c0e044ddc3cdf0b64b2_Delhi-Footer-Thumbnail_32_11.jpg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c6f3ea94d66b7dc5c199ec_63be46e3508ab6f2c169d78e_2ec6dbebf77fe703dc92d325b6d7b461.png', 'https://demo.exploro.com/3rdparty/gde/videos/Delhi_49%20megs.mp4', ARRAY[''], 1, 5);


INSERT INTO country (name, slug, description_long, description_short, image_link, thumbnail_link, special_offer_image_link, video_link, gallery, featured_country, continent) VALUES ('Jamaica', 'jamaica', 'Exercitationem assumenda officia eos in dolorem fuga. Et repellat ratione et labore corrupti est repudiandae', 'Dolorem recusandae eos nulla asperiores. Ut fugit rem odit et ut repellat mollitia saepe non. Mollitia ratione ad sint occaecati. Accusamus', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c6f1c74f7c700a2e55f858_1673982407356-image7.jpg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c6f8a0ec27fa8cbe7f3bb3_Country-Jamaica-Thumbnail.jpg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c6f3ea94d66b7dc5c199ec_63be46e3508ab6f2c169d78e_2ec6dbebf77fe703dc92d325b6d7b461.png', 'https://spirit.exploro.com/3rdparty/gde/videos/jamaica-hero.mp4', ARRAY[''], 2, 6);


INSERT INTO country (name, slug, description_long, description_short, image_link, thumbnail_link, special_offer_image_link, video_link, gallery, featured_country, continent) VALUES ('United Kingdom', 'united-kingdom', 'The United Kingdom of Great Britain and Northern Ireland is a constitutional monarchy comprised of most of the British Isles. The UK is four constituent countries; England, Northern Ireland, Scotland, and Wales. Although there are similarities across the countries, each region has its unique history, landscape, and exciting opportunities to offer the traveler. The UK is responsible for creating five significant sports: golf, rugby, cricket, lawn tennis, and, of course, football (or soccer, for Americans). Scattered throughout the country are castles, forts, and monolithic stone structures, many dating back thousands of years. Hundreds of battles and countless disputes took place over the chaotic history of the region. There are thousands of years of history to observe as you tour the many sites. The capital and largest city is London, a truly global metropolis like no other. London is a city once occupied by the Romans, and located at the confluence of ancient kingdoms. The country welcomes over 30 million visitors to its shores each year.', 'The United Kingdom of Great Britain and Northern Ireland is a constitutional monarchy comprised of most of the British Isles.', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4b823f740ee1e7a7d63_63c8828fd690b8f7c1320bdb_london-banner.jpeg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4b823f740a7a57a7d62_63c88294bde991f55d4007ab_London-Footer-Thumbnail_5.jpeg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4b73c6fd615560a96b5_63c6f3ea94d66b7dc5c199ec_63be46e3508ab6f2c169d78e_2ec6dbebf77fe703dc92d325b6d7b461.png', '', ARRAY[''], 1, 3);


INSERT INTO country (name, slug, description_long, description_short, image_link, thumbnail_link, special_offer_image_link, video_link, gallery, featured_country, continent) VALUES ('Vietnam', 'vietnam', 'The unique S-shaped country of Vietnam is officially known as the Socialist Republic of Vietnam. It is a country with a rich and violent history, located on the eastern edge of Southeast Asia. The country has a population of over 96 million, which makes it the world’s fifteenth-most populous country. Despite its turbulent past, Vietnam is one of the fastest-growing economies of the 21st century. It became a unified country in 1975 when the armed forces of the Communist north seized the south. Today the country is famous for its bustling Hanoi and Ho Chi Minh cities and popular Instagram destinations like Ha Long Bay, the Mekong Delta, and Da Nang. Scattered throughout the country are remnants of its colonial past, such as the French architecture and American military vehicles.', 'The unique S-shaped country of Vietnam is officially known as the Socialist Republic of Vietnam. It is a country with a rich and violent history, located on the eastern edge of Southeast Asia.', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4be25c83618c2e3caf8_banner_49.jpeg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4be25c8364fefe3caf9_banner_49.jpeg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4b73c6fd615560a96b5_63c6f3ea94d66b7dc5c199ec_63be46e3508ab6f2c169d78e_2ec6dbebf77fe703dc92d325b6d7b461.png', '', ARRAY[''], 2, 5);


INSERT INTO country (name, slug, description_long, description_short, image_link, thumbnail_link, special_offer_image_link, video_link, gallery, featured_country, continent) VALUES ('Malaysia', 'malaysia', 'Founded in 1857 under British rule as a tin mining outpost, Kuala Lumpur is fairly new as far as Malaysian cities go and lacks the rich history of Georgetown or Malacca. Due to the success of tin mining, Kuala Lumpur began to flourish, but had problems with gang fighting in the late 1800s. Following this, Kuala Lumpur faced further misfortune after much of the city burnt down in a large fire as most buildings were built from wood and thatch. As a result, buildings in Kuala Lumpur were required to be built with brick and tile. After these rough early years, Kuala Lumpur began to prosper and was made capital of the Federated Malay States in 1896.', 'Kuala Lumpur began to prosper and was made capital of the Federated Malay States in 1896.', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c24e122405e73ee0c4fed4_kl-main-banner.jpg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c24e2474f93405aa9fd49f_Kuala%20Lumpur-Thumbnail_8_3_5.jpg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c6f3ea94d66b7dc5c199ec_63be46e3508ab6f2c169d78e_2ec6dbebf77fe703dc92d325b6d7b461.png', 'https://demo.exploro.com/3rdparty/gde/videos/Kuala%20Lumpur%20NT_0.mp4', ARRAY[''], 2, 5);


INSERT INTO country (name, slug, description_long, description_short, image_link, thumbnail_link, special_offer_image_link, video_link, gallery, featured_country, continent) VALUES ('Norway', 'norway', 'Norway is known for its deep fjords along its west coast. It is the westernmost, northernmost, as well as easternmost of the three Scandinavian countries. Norway stretches from the daring North Sea near Denmark to robust Scotland and into the cold Arctic Ocean. Norway is well known for its unique and varied scenery. The fjords in the country’s west are long narrow inlets flanked on either side by tall mountains where the sea penetrates far inland. Norway is known for its magical skies, amazing landscapes, Vikings and folklore, and eco-friendly environment.', '', '', '', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4b73c6fd615560a96b5_63c6f3ea94d66b7dc5c199ec_63be46e3508ab6f2c169d78e_2ec6dbebf77fe703dc92d325b6d7b461.png', '', ARRAY[''], 2, 3);


INSERT INTO country (name, slug, description_long, description_short, image_link, thumbnail_link, special_offer_image_link, video_link, gallery, featured_country, continent) VALUES ('Aruba', 'aruba', 'Aruba is a medium-sized island that is 19.6 miles long, and approximately 70 square miles. It''s a great destination because even though it is located in a sunny place globally, there is a constant breeze, keeping it at an enjoyable temperature almost every day. Additionally, Aruba has the lowest risk of rain in the Caribbean. Aruba offers excellent food, fun activities, and breathtaking scenery. Enjoy your time in Aruba by relaxing on the beach, boating, golfing, diving and snorkeling, to name a few activities. There is something for everyone in Aruba!', 'Aruba offers excellent food, fun activities, and breathtaking scenery. Enjoy your time in Aruba by relaxing on the beach, boating, golfing, diving and snorkeling, to name a few activities.', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8708c1e590c4e46b87dd7_63be477c2f025b3d085de908_Country-Aruba-Thumbnail.jpg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8708c1e590c4e46b87dd7_63be477c2f025b3d085de908_Country-Aruba-Thumbnail.jpg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c6f3ea94d66b7dc5c199ec_63be46e3508ab6f2c169d78e_2ec6dbebf77fe703dc92d325b6d7b461.png', 'https://spirit.exploro.com/3rdparty/gde/videos/aruba-hero.mp4', ARRAY[''], 2, 6);


INSERT INTO country (name, slug, description_long, description_short, image_link, thumbnail_link, special_offer_image_link, video_link, gallery, featured_country) VALUES ('Burundi', 'burundi', 'Burundi is known as the Republic of Burundi and is one of the smallest countries in Africa. It is known in Swahili as Jamuhuri ya Burundi and République du Burundi in French. The official languages of Burundi are Kirundi, French, and English. Kirundi is the official national language. Burundi is in the Great Rift Valley and is a landlocked country. Many who visit take advantage of the nearby African Great Lakes region. Rwanda borders it to the north, Tanzania to the east and southeast, and the Democratic Republic of the Congo to the west. On the southwestern border rests the large Lake Tanganyika. The country has two capital cities, Gitega and Bujumbura, and Bujumbura is the largest city in the country. Much of the land is used for agriculture and animal grazing.', '', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4b8caee12a795870ca5_burundi-banner.jpeg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4b8caee121336870ca4_burundi-banner.jpeg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4b73c6fd615560a96b5_63c6f3ea94d66b7dc5c199ec_63be46e3508ab6f2c169d78e_2ec6dbebf77fe703dc92d325b6d7b461.png', '', ARRAY[''], 2);


INSERT INTO country (name, slug, description_long, description_short, image_link, thumbnail_link, special_offer_image_link, video_link, gallery, featured_country) VALUES ('Cameroon', 'cameroon', 'Cameroon is a country in Central Africa and is one of the smaller countries on the massive African continent, yet many see Cameroon as large as Africa itself. Western tourism is rare, although many tourists come from Europe, primarily from Belgium. Cameroon is a highly diverse and multi-ethnic country. There are French-speaking regions as well as regions where English dominates. Some areas of the country are very Christian, while others are predominately Muslim. These diverse people live primarily in peace, enjoying a country often referred to as "Africa in Miniature," Cameroon contains the tallest mountain in Central Africa and a wide diversity of terrain that includes rain forests, desert plains, mountains, and high plateaus.', '', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4b81bf36ab5323dbe88_cameroon-banner.jpeg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4b81bf36a571a3dbe87_cameroon-banner.jpeg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4b73c6fd615560a96b5_63c6f3ea94d66b7dc5c199ec_63be46e3508ab6f2c169d78e_2ec6dbebf77fe703dc92d325b6d7b461.png', '', ARRAY[''], 2);


INSERT INTO country (name, slug, description_long, description_short, image_link, thumbnail_link, special_offer_image_link, video_link, gallery, featured_country, continent) VALUES ('Canada', 'canada', 'Canada is the largest country in North America by land area and second in the world behind Russia. Renowned worldwide for its vast, untouched, seemingly magical landscape, it is home to a beautiful blend of cultures from around the world and interesting, multifaceted history. Additionally, Canada is one of the world’s wealthiest countries, showcased by its universal healthcare. It is a major tourist destination due to its undeniable natural beauty and smartly placed attractions.', '', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4b825c836e815e3cae4_canada-banner_0.jpeg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4b825c8369106e3cae5_canada-banner_0.jpeg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4b73c6fd615560a96b5_63c6f3ea94d66b7dc5c199ec_63be46e3508ab6f2c169d78e_2ec6dbebf77fe703dc92d325b6d7b461.png', '', ARRAY[''], 2, 4);


INSERT INTO country (name, slug, description_long, description_short, image_link, thumbnail_link, special_offer_image_link, video_link, gallery, featured_country) VALUES ('Central African Republic', 'central-african-republic', 'The Central African Republic can be found in the very heart of Africa. It is one of the best places to enjoy traditional African wildlife. Political unrest and civil wars have led to many years of less than ideal conditions, but many locals take heart in hope for the future. There is a wide diversity of food throughout the country, including Chinese, Lebanese, French, and traditional local dishes. The country has many mineral deposits and other natural resources, such as uranium, crude oil, gold, diamond, cobalt, lumber, and hydropower. However, it is among the ten poorest countries globally.', '', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4b87d5d847a1a382258_the-central-african-republic-banner.jpeg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4b87d5d845641382257_the-central-african-republic-banner.jpeg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4b73c6fd615560a96b5_63c6f3ea94d66b7dc5c199ec_63be46e3508ab6f2c169d78e_2ec6dbebf77fe703dc92d325b6d7b461.png', '', ARRAY[''], 2);


INSERT INTO country (name, slug, description_long, description_short, image_link, thumbnail_link, special_offer_image_link, video_link, gallery, featured_country, continent) VALUES ('China', 'china', 'China is the world’s oldest civilization and has the world’s largest population. The country has made remarkable advances over the last fifty years, transforming from a poverty-stricken country to one of the world’s leading economies. Its long and rich history is well preserved in the current citizens’ thinking and values and in the unique art, architecture, and feats of engineering that remain from past dynasties. China has seen phenomenal advances and changes during the tumultuous 20th century. Of course, there are growing pains from turning peasant villages into mega metropolitan centers. China is one of the most visited, impressive and influential countries. In today’s world, you can still see relics of the past and enjoy the modern with the ancient.', '', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4b8a4afa6368639fed7_china-banner.jpeg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4b8a4afa6368639fed7_china-banner.jpeg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4b73c6fd615560a96b5_63c6f3ea94d66b7dc5c199ec_63be46e3508ab6f2c169d78e_2ec6dbebf77fe703dc92d325b6d7b461.png', '', ARRAY[''], 2, 5);


INSERT INTO country (name, slug, description_long, description_short, image_link, thumbnail_link, special_offer_image_link, video_link, gallery, featured_country) VALUES ('colombia', 'colombia', 'Located on the southwest point of South America, Colombia is an environmentally diverse island double the size of France. The beaches on the island are incredible and provide the perfect laidback experience in the Caribbean. Besides being known for its beaches, the country also has competitive salsa and late-night dance parties in bars and nightclubs.', 'Besides being known for its beaches, the country also has competitive salsa and late-night dance parties in bars and nightclubs.', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c87ab95b2dcabf8cb9b18f_colombia-banner.jpg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c4b95bce5aa22a3ee650a7_Country-Colombia-Thumbnail.jpg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c6f3ea94d66b7dc5c199ec_63be46e3508ab6f2c169d78e_2ec6dbebf77fe703dc92d325b6d7b461.png', 'https://spirit.exploro.com/3rdparty/gde/videos/colombia-.mp4', ARRAY[''], 2);


INSERT INTO country (name, slug, description_long, description_short, image_link, thumbnail_link, special_offer_image_link, video_link, gallery, featured_country, continent) VALUES ('Comoros', 'comoros', 'Comoros consists of three islands in the Indian Ocean, at the northern end of the Mozambique Channel off the eastern coast of Africa. The country is known as the Union of Comoros. It is one of the world’s poorest countries, but what it lacks in economic resources, it makes up for in natural beauty. A young and rapidly increasing population combined with a lack of abundant natural resources has led to employment and transportation issues. The name Comoros originates from “Qamar," which is Arabic for the moon. The capital city Moroni is also its largest city. Comoros has three official languages; Comorian, French, and Arabic and the official state religion is Sunni Islam. It is the only country in the Arab League entirely in the Southern Hemisphere.', '', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4b891c3e32814f240c4_comoros-banner.jpeg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4b891c3e32814f240c4_comoros-banner.jpeg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4b73c6fd615560a96b5_63c6f3ea94d66b7dc5c199ec_63be46e3508ab6f2c169d78e_2ec6dbebf77fe703dc92d325b6d7b461.png', '', ARRAY[''], 2, 1);


INSERT INTO country (name, slug, description_long, description_short, image_link, thumbnail_link, special_offer_image_link, video_link, gallery, featured_country) VALUES ('Cost Rica', 'cost-rica', 'Costa Rica is a great destination if you love nature and ecotourism because it has abundant natural parks and protected areas. The biodiversity of plants and animals is one of the most diverse in the world. There are beaches, mountains, rainforests, and incredible national parks. Visitors can enjoy many outdoor activities like river rafting, cave tubing, zip lining, and canoeing. The beaches are beautiful on both the Caribbean and Pacific sides, and you can enjoy an exciting tropical vacation experience in Costa Rica.', 'Costa Rica is a great destination if you love nature and ecotourism because it has abundant natural parks and protected areas. The biodiversity of plants and animals is one of the most diverse in the world.', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c879a5d690b8e529314e81_costa-rica-banner.jpg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c879abdaee1683441ecf1a_Country-Costa%20Rica-Thumbnail.jpg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c6f3ea94d66b7dc5c199ec_63be46e3508ab6f2c169d78e_2ec6dbebf77fe703dc92d325b6d7b461.png', 'https://spirit.exploro.com/3rdparty/gde/videos/costa-rica-hero.mp4', ARRAY[''], 2);


INSERT INTO country (name, slug, description_long, description_short, image_link, thumbnail_link, special_offer_image_link, video_link, gallery, featured_country, continent) VALUES ('Democratic Republic of the Congo', 'democratic-republic-of-the-congo', 'The Democratic Republic of Congo is in located in the Congo Basin. The area has one of the oldest histories of any country, with the territory of the DRC first inhabited by Central African foragers around 90,000 years ago! The area has undergone many reformations and seen a variety of leadership. Today, the country is the largest and most populous country in Central Africa and the largest French-speaking country in the world. The Democratic Republic of the Congo has plenty of natural resources, There is natural beauty and wonderment in the mountains and beautiful streams found throughout the countryside.&nbsp; The Great Lake Kivu is expansive and beautiful with small fishing villages.&nbsp; It also provides many options for the sports enthusiasts.&nbsp; DRC is also home to mountain gorillas, which can be found in Virunga National Park.', '', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4b925c83651f9e3cae9_democratic-republic-of-the-congo-banner.jpeg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4b925c836f453e3cae8_democratic-republic-of-the-congo-banner.jpeg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4b73c6fd615560a96b5_63c6f3ea94d66b7dc5c199ec_63be46e3508ab6f2c169d78e_2ec6dbebf77fe703dc92d325b6d7b461.png', '', ARRAY[''], 2, 3);


INSERT INTO country (name, slug, description_long, description_short, image_link, thumbnail_link, special_offer_image_link, video_link, gallery, featured_country, continent) VALUES ('Denmark', 'denmark', 'Once the seat of Vikings and later a significant north European power, Denmark has evolved into a modern, prosperous nation participating in Europe’s general political and economic integration. The awe-inspiring country hosts a rich, well-preserved cultural heritage, showcasing Dane’s legendary sense of design and architecture. Denmark is a society often seen as a benchmark of civilization, with progressive social policies and a commitment to free speech. Denmark is a beautiful country with a stunning coastal peninsula and charming island communities with a peaceful environment that makes Denmark a special place to visit.', '', '', '', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4b73c6fd615560a96b5_63c6f3ea94d66b7dc5c199ec_63be46e3508ab6f2c169d78e_2ec6dbebf77fe703dc92d325b6d7b461.png', '', ARRAY[''], 2, 3);


INSERT INTO country (name, slug, description_long, description_short, image_link, thumbnail_link, special_offer_image_link, video_link, gallery, featured_country, continent) VALUES ('Dominican Republic', 'dominican-republic', 'The first European settlement founded on the Americas continent was the Dominican Republic. The country’s first settlement, Santo Domingo, has been dedicated by UNESCO. The Dominican Republic is sustainable since it produces most foods served across the country. The climate is warm in the Dominican Republic, with very little temperament change and plentiful rainfall for crops and climate control. People visit the Dominican Republic to enjoy the resorts, golfing, and, most of all, its beaches, and you will find intriguing history, rich culture, and beautiful scenery throughout the country.', '', '', '', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4b73c6fd615560a96b5_63c6f3ea94d66b7dc5c199ec_63be46e3508ab6f2c169d78e_2ec6dbebf77fe703dc92d325b6d7b461.png', 'https://media-dev.exploro.com/inflight-media/dominican-republic-.mp4', ARRAY[''], 2, 6);


INSERT INTO country (name, slug, description_long, description_short, image_link, thumbnail_link, special_offer_image_link, video_link, gallery, featured_country) VALUES ('Ecuador', 'ecuador', 'Ecuador is a pretty country with a diverse landscape, including beautiful beaches, impressive mountains, and thick rainforests. There are waterfalls, active volcanoes, and Incan ruins to explore. Ecuador is also an isolated archipelago world-renowned for its unique wildlife and diverse rainforests, fauna, and flowers. There are over 4,000 species of orchids in Ecuador. What a beautiful sight! Ecuador’s mainstream culture has African elements but is mainly a traditionally Spanish heritage. You can check this out at one of the many markets operating across the country.', '', '', '', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4b73c6fd615560a96b5_63c6f3ea94d66b7dc5c199ec_63be46e3508ab6f2c169d78e_2ec6dbebf77fe703dc92d325b6d7b461.png', 'https://media-dev.exploro.com/inflight-media/ecuador-hero.mp4', ARRAY[''], 2);


INSERT INTO country (name, slug, description_long, description_short, image_link, thumbnail_link, special_offer_image_link, video_link, gallery, featured_country) VALUES ('El Salvador', 'el-salvador', 'El Salvador is located halfway between Guatemala and Honduras and is covered in an abundance of beautiful beaches, lush forests, countless volcanoes, Mayan ruins, rich history, and amazing culture. El Salvador is the most densely populated and smallest country in Central America. While it may be small, El Salvador is full of diversity, with fourteen lakes, four large cities, and twenty-five volcanoes, a few of which are still active today. Come to El Salvador and enjoy great food, archaeological sites, arts and crafts, and a litany of outdoor activities.', '', '', '', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4b73c6fd615560a96b5_63c6f3ea94d66b7dc5c199ec_63be46e3508ab6f2c169d78e_2ec6dbebf77fe703dc92d325b6d7b461.png', 'https://media-dev.exploro.com/inflight-media/el-salvador-hero.mp4', ARRAY[''], 1);


INSERT INTO country (name, slug, description_long, description_short, image_link, thumbnail_link, special_offer_image_link, video_link, gallery, featured_country) VALUES ('Ethiopia', 'ethiopia', 'Ethiopia is officially known as the Federal Democratic Republic of Ethiopia, and is one of the oldest independent nations in the world. Additionally, it is one of the world’s oldest Christian states, beat only by Armenia. Ethiopia is a large country, comprising over a million square kilometers (420,000 square miles) and over 117 million citizens. It is the 2nd-most populous country in Africa and the 12th largest globally. Ethiopia holds a very distinctive honor. Uniquely among African countries, Ethiopia was never colonized. The local people maintained their independence while Europe pillaged Africa. The only exception was from 1936 to 1941 when it was under Italian military occupation. The English name "Ethiopia" is thought to be derived from the Greek word “Aithiopia”. Ethiopia belongs to many organizations. It is a member of the League of Nations, signed the Declaration by United Nations in 1942, founded the UN headquarters in Africa, and was one of the 51 original members of the UN. Ethiopia is a very ecologically diverse country with deserts along the eastern border and tropical forests in the south.&nbsp; The Ethiopian Highlands are the largest continuous mountain ranges in Africa.', '', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4b9a4afa62ce039fee2_ethiopia-banner.jpeg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4b9a4afa62ce039fee2_ethiopia-banner.jpeg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4b73c6fd615560a96b5_63c6f3ea94d66b7dc5c199ec_63be46e3508ab6f2c169d78e_2ec6dbebf77fe703dc92d325b6d7b461.png', '', ARRAY[''], 2);


INSERT INTO country (name, slug, description_long, description_short, image_link, thumbnail_link, special_offer_image_link, video_link, gallery, featured_country) VALUES ('Faroe Islands', 'faroe-islands', 'The Faroe Islands consist of 750 total islands in the Atlantic Ocean on the coast of Norway, though 18 are considered primary. The island chain is within proximity of Norway, but Denmark is the governing authority. However, in most factions, the Faroe Islands have an autonomous government. The island chain comprises 540 square miles of land and has a population of 53,882. Bridges or undersea tunnels connect many islands, but some require a boat, plane, or helicopter to visit.&nbsp; Visiting the Faroe Islands will take you off the well-beaten path. You will experience grass-topped houses, gorgeous landscapes with rolling green hills, and untamed wilderness. The unspoiled landscape and impressive bird cliffs are a must-see. When visiting the Faroe Islands, the best thing to do is enjoy some downtime and relax.', '', '', '', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4b73c6fd615560a96b5_63c6f3ea94d66b7dc5c199ec_63be46e3508ab6f2c169d78e_2ec6dbebf77fe703dc92d325b6d7b461.png', '', ARRAY[''], 2);


INSERT INTO country (name, slug, description_long, description_short, image_link, thumbnail_link, special_offer_image_link, video_link, gallery, featured_country) VALUES ('Ghana', 'ghana', 'Based on archaeological evidence, humans have lived in and around the area that makes up present-day Ghana from as far back as 1500 BC. However, there is no archeological evidence that those early dwellers are related to the area’s current inhabitants. In the 1400s, Europeans made their way to Ghana, with the Portuguese being the first country to invade. The Dutch followed in the next century, and then the English, Danes, and Swedes in the following century. These foreigners flocked to the area because of the large availability of gold. Today, any world traveler will recommend that Ghana is an excellent country for first-time visitors to Africa, sometimes called “Africa for beginners." &nbsp; Ghana has a robust infrastructure, political stability, and English is the predominately spoken language. You will find the people are generally accommodating and welcoming. Tourism in Ghana has been growing quickly, and tour operators report a significant increase in visits to Ghana.', '', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4ba6cdfbd3d2dcf4f69_ghana-banner_1.jpeg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4ba6cdfbdc8e5cf4f6a_ghana-banner_1.jpeg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4b73c6fd615560a96b5_63c6f3ea94d66b7dc5c199ec_63be46e3508ab6f2c169d78e_2ec6dbebf77fe703dc92d325b6d7b461.png', '', ARRAY[''], 2);


INSERT INTO country (name, slug, description_long, description_short, image_link, thumbnail_link, special_offer_image_link, video_link, gallery, featured_country) VALUES ('Guatemala', 'guatemala-2', 'The naturally beautiful landscape is a constant draw for people to visit Guatemala with its exciting and scenic environment. The Mirador region is known for the Mayan ruins, with countless remnants of their reign throughout the country. The climate in Guatemala is temperate; if you want desert warmth in the morning and rainfall in the afternoon, you can find it all. The culture is distinct and rich, and Guatemalans value family, honesty, honor, education, and work. Guatemala allows you to connect with nature and immerse yourself in the local culture.', 'The climate in Guatemala is temperate; if you want desert warmth in the morning and rainfall in the afternoon, you can find it all.', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c4b7370c0a8e67b3e1bba6_guatemala-banner.jpg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c6f86094d66bc17ec1d445_Country-Guatemala-Thumbnail.jpg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c6f3ea94d66b7dc5c199ec_63be46e3508ab6f2c169d78e_2ec6dbebf77fe703dc92d325b6d7b461.png', 'https://spirit.exploro.com/3rdparty/gde/videos/costa-rica-hero.mp4', ARRAY[''], 2);


INSERT INTO country (name, slug, description_long, description_short, image_link, thumbnail_link, special_offer_image_link, video_link, gallery, featured_country, continent) VALUES ('Haiti', 'haiti', 'The Republic of Haiti is full of rich history and culture, which has shaped Haiti into what it is today. Haiti was a place of natural disasters and poverty in the past. Yet, it has grown to be a popular and unique destination today. Even though it can be subject to intense storms, Haiti is the most mountainous country in the Caribbean, with a broad, flat central plain to the north. While Haiti was initially inhabited by the native tribe Taino, Christopher Columbus officially discovered Haiti in 1492. He was buried in Haiti; today, there is a monument of Christopher Columbus in Port-au-Prince, the capital of Haiti. There are cave paintings from the Taino people throughout the country. The paintings are now considered national symbols and one of the country’s unique attractions. Haiti is known for its colorful, symbolic, and bold colors throughout the country. It has one of the highest levels of biodiversity in the Caribbean, with over 5,600 plant types. The official languages of Haiti are French and Creole, and Voodoo is an officially recognized religion. People visit Haiti from around the world to enjoy its culture, landscape, art, and music.', '', '', '', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4b73c6fd615560a96b5_63c6f3ea94d66b7dc5c199ec_63be46e3508ab6f2c169d78e_2ec6dbebf77fe703dc92d325b6d7b461.png', 'https://media-dev.exploro.com/inflight-media/haiti-hero-.mp4', ARRAY[''], 2, 6);


INSERT INTO country (name, slug, description_long, description_short, image_link, thumbnail_link, special_offer_image_link, video_link, gallery, featured_country, continent) VALUES ('Honduras', 'honduras', 'You will find Honduras in Central America. It is the second-largest country and promotes a significant opportunity for travelers to see amazing sights, have incredible experiences and enjoy the diverse wildlife. Honduras is known for its rich natural resources, including minerals, coffee, tropical fruit, and sugar cane. People who love spending time outdoors will love Honduras. There are national parks, unique diving locations, fantastic beaches for lounging or snorkeling, and ancient ruins and villages to explore. Locals are friendly, and family plays a vital role in Honduras society.&nbsp;', '', '', '', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4b73c6fd615560a96b5_63c6f3ea94d66b7dc5c199ec_63be46e3508ab6f2c169d78e_2ec6dbebf77fe703dc92d325b6d7b461.png', 'https://media-dev.exploro.com/inflight-media/honduras-hero.mp4', ARRAY[''], 2, 6);


INSERT INTO country (name, slug, description_long, description_short, image_link, thumbnail_link, special_offer_image_link, video_link, gallery, featured_country, continent) VALUES ('Italy', 'italy', 'Italy is one of the most famous countries in the world. For millennia, the inhabitants have had a profound impact on world history. Italy is known for its iconic boot-shaped peninsula jutting into the Adriatic, Tyrrhenian, and Mediterranean seas. This central location has led to the city playing an important role in its history. The country has some of the best natural defenses anywhere. The sea surrounds Italy, and massive mountains crisscross the interior, dividing it into regions and protecting from invasion.
Further north, the Alps cut across the top of the country, providing a nearly impenetrable mountain barrier. Many of the population live in the wooded hills, home to Italy’s historic cities, including Rome. In the south are hot, dry coastlands mixed with fertile plains where olives, almonds, and figs are grown. You can find Italian art, architecture, and culture in cities worldwide. Italy was home to Leonardo da Vinci and Michelangelo, two of the most well-known artists in the world. For thousands of years, Italy has also been the heart of the Catholic Church, which is governed by Vatican City, a landlocked city that functions as a country located in central Rome. Italy is big on family, and in many ways, it is at center of Italian society. Regardless of employment status, young people often live at home until they are in their 30s. And on the flip side, when parents retire, they often move in with their children.', '', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4ba25c8366985e3caed_italy-banner.jpeg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4ba25c8366507e3caec_italy-banner.jpeg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4b73c6fd615560a96b5_63c6f3ea94d66b7dc5c199ec_63be46e3508ab6f2c169d78e_2ec6dbebf77fe703dc92d325b6d7b461.png', '', ARRAY[''], 2, 3);


INSERT INTO country (name, slug, description_long, description_short, image_link, thumbnail_link, special_offer_image_link, video_link, gallery, featured_country) VALUES ('Ivory Coast', 'ivory-coast', 'Côte d’Ivoire, or the Ivory Coast in West Africa, is where the continent meets the sea. In a bid for further independence, the country’s officials have asked that the country no longer be called the "Ivory Coast", and instead have requested that it be called "Côte d’Ivoire" (the equivalent in French). Although English speakers often struggle with French accents, pronouncing the country as "Coat di-VWAR" will make sense to the locals. People worldwide visit it for its beaches, rainforest, wildlife, and local tourist villages. Over 24 million people live in this country, and tourism is one of the major industries. Côte d’Ivoire is home to more than 60 ethnic groups, but the Baoule are the largest ethnic group. It is wise to avoid tap water and prioritize bottled water when visiting. Most of the country’s citizens live in flat coastal areas, and the wooded areas to the west are relatively unpopulated. The Ivory Coast offers beautiful beaches, soaring mountains, and massive rainforests to those who visit.', '', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4ba886de8263eede8d8_ivory-coast-banner.jpeg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4ba886de8d0c5ede8d9_ivory-coast-banner.jpeg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4b73c6fd615560a96b5_63c6f3ea94d66b7dc5c199ec_63be46e3508ab6f2c169d78e_2ec6dbebf77fe703dc92d325b6d7b461.png', '', ARRAY[''], 2);


INSERT INTO country (name, slug, description_long, description_short, image_link, thumbnail_link, special_offer_image_link, video_link, gallery, featured_country) VALUES ('Kenya', 'kenya-f', 'Kenya is a truly African country. Many safaris take place in this beautiful country due to its abundance of African natural wildlife. The iconic Mount Kilimanjaro dominates the landscape to the south, bordering Tanzania, jutting high into the sky. Snow is seen at its peak year-round. Going along with the natural theme of the area, the 60 breathtaking national parks and game reserves that Kenya is known for are calling your name! The 7th wonder of the world, where wildebeests migrate to the Masai Mara, is located in Kenya. This fascinating event sees over a million wildebeests traveling many miles chasing rainwater to survive the dry season. World-famous scenery such as the white-capped Mount Kenya and the Great Rift Valley, tea plantations at Kerich, and coffee plantations at Thika draw visitors worldwide to Kenya. Although the country is famous for its natural landscapes, many historical mosques and colonial-era forts are located throughout the country. Thanks to the abundance of wildlife, many consider Kenya to be the safari epicenter of the world. There are three UNESCO Natural World Heritage Sites in Kenya; Mount Kenya National Park, Mijikenda Kaya Forests, and Lake Turkana National Park. The national parks and reserves spread across the country make up more than 17,000 square miles or 8% of Kenya’s total landmass.', '', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4bb23ecaaaf2da391aa_kenya-banner.jpeg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4bb23ecaa0c94a391ab_kenya-banner.jpeg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4b73c6fd615560a96b5_63c6f3ea94d66b7dc5c199ec_63be46e3508ab6f2c169d78e_2ec6dbebf77fe703dc92d325b6d7b461.png', '', ARRAY[''], 2);


INSERT INTO country (name, slug, description_long, description_short, image_link, thumbnail_link, special_offer_image_link, video_link, gallery, featured_country) VALUES ('Malawi', 'malawi', 'Malawi is a name you may not have heard, but you are likely familiar with many of the country’s neighbors. Malawi is nestled between three well-known African countries, including Mozambique, Zambia and Tanzania. Malawi is well known for its breathtaking natural beauty, highlighted by highlands split by the Great Rift Valley and the enormous Lake Malawi. The lake has been a home and lifeblood to generations of people, and today the southern end serves as Lake Malawi National Park. This National Park protects diverse wildlife, from the startling colorful fish to the aggressive baboons. The deep clear waters make it a popular spot for diving and boating. Many travelers describe Malawi as the "Warm Heart of Africa," which refers to the friendliness and overall helpfulness of the local people. Malawi is an independent and progressive nation.&nbsp;', '', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4bb7d5d84582938226b_malawi-banner_1.jpeg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4bb7d5d8429f838226a_malawi-banner_1.jpeg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4b73c6fd615560a96b5_63c6f3ea94d66b7dc5c199ec_63be46e3508ab6f2c169d78e_2ec6dbebf77fe703dc92d325b6d7b461.png', '', ARRAY[''], 2);


INSERT INTO country (name, slug, description_long, description_short, image_link, thumbnail_link, special_offer_image_link, video_link, gallery, featured_country) VALUES ('Mauritius', 'mauritius', 'Mauritius is an incredibly unique African nation, a collection of islands located off the coast of Madagascar (which is itself, incidentally, an island of the eastern coast of the African Continent) in the Indian Ocean. Mauritius is about 2,300 km (or 1,400 miles) from Africa. The country con-sists of the main island of Mauritius and the smaller islands of Rodrigues, the Agalegas, and the Cargados Carajos Shoals. People from several countries discovered the main island of Mauritius in the 9th and 16th centuries, but chose not to settle in the lush forest paradise. The first people to establish a colony on the island were the Dutch, who decided on the official name for the settlement in 1598. The Dutch exploited many of the island’s natural resources and then abandoned the settlement. The French settled the land in 1712 and eventually Mauritius became an independent nation in 1968. &nbsp;A stable democracy and a glowing human rights record means Mauritius has attracted considerable foreign investment and has one of Africa’s highest per capita incomes. Mauritius is known for its beaches, lagoons and reefs. The mountains are located in the middle area of the island and include Black River Gorges National Park, with rain-forests, waterfalls, hiking trails and wildlife. Capital Port Louis has sites such as Eureka plantation house, botanical gardens and the Champs de Mars horse track.', '', '', '', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4b73c6fd615560a96b5_63c6f3ea94d66b7dc5c199ec_63be46e3508ab6f2c169d78e_2ec6dbebf77fe703dc92d325b6d7b461.png', 'https://media-dev.exploro.com/inflight-media/Mauritius,%20Mauritius.mp4', ARRAY[''], 2);


INSERT INTO country (name, slug, description_long, description_short, image_link, thumbnail_link, special_offer_image_link, video_link, gallery, featured_country) VALUES ('Mexico', 'mexico', 'Mexico is known for its incredible cuisine, beautiful ancient and modern art, fascinating archaeology, and incredible history, including the pyramids, Spanish music, and several museums. The country is also blessed with miles of shoreline that allow visitors to experience all the beautiful beaches have to offer, including snorkeling, sunbathing, boating, and fishing, to name a few. You will want to check out its historical sites, festive drinks, and spicy cuisine. The weather is very versatile with little fluctuation of temperature from season to season. It can include snow-capped mountains in the Sierras, rainy jungles in the Southeast, and warm, hot deserts in the Northwest. Come and enjoy the colorful and vibrant culture of Mexico.', 'Nemo vel sint quibusdam ad explicabo rerum. Error ex harum tempore. Et accusamus voluptates et laborum qui aut ea consequatur molestiae', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c6f1c70d1dab17f73cb95d_1673982407358-image10.jpg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c6f8c836b53cd9494c5b15_Country-Mexico-Thumbnail.jpg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c6f3ea94d66b7dc5c199ec_63be46e3508ab6f2c169d78e_2ec6dbebf77fe703dc92d325b6d7b461.png', 'https://demo.exploro.com/3rdparty/gde/videos/El%20AL%20Hero.mp4', ARRAY[''], 2);


INSERT INTO country (name, slug, description_long, description_short, image_link, thumbnail_link, special_offer_image_link, video_link, gallery, featured_country) VALUES ('Mozambique', 'mozambique', 'Mozambique was initially a Portuguese settlement, started in the late 1400s and was an important port and highly coveted by competing powers throughout the centuries. The country was eventually able to declare independence in 1975. The central and southern areas are home to some of the best things Africa has to offer. Mozambique is a tropical country, with the majority of its land lying on the coast. As such, it enjoys warm weather year-round. Mozambique is also a country of contrasts, and the higher mountain areas have a different climate and lower temperatures. Mozambique is a beautiful and fun destination.', '', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4bb98ae6e916df1ab2a_mozambique-banner.jpeg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4bb98ae6e9330f1ab2b_mozambique-banner.jpeg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4b73c6fd615560a96b5_63c6f3ea94d66b7dc5c199ec_63be46e3508ab6f2c169d78e_2ec6dbebf77fe703dc92d325b6d7b461.png', '', ARRAY[''], 2);


INSERT INTO country (name, slug, description_long, description_short, image_link, thumbnail_link, special_offer_image_link, video_link, gallery, featured_country) VALUES ('Nicaragua', 'nicaragua', 'You can find Nicaragua in Central America. It is the largest country and is nicknamed "The Country of Lakes and Volcanoes" by the locals. Nicaragua provides some of the best volcano hikes in Central America. The particular topography is distinctive and incredibly breathtaking to the area. Nicaragua has the two largest freshwater lakes in Central America. Lake Nicaragua is the largest source of freshwater in Nicaragua and offers marine ocean animals, including sharks, swordfish, and tarpon. Nicaragua has amazing food and beautiful white sandy beaches and turquoise waters, offering opportunities for surfing, horseback riding, fishing, swimming, and even yoga. Come check these out. There is something for everyone.', '', '', '', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4b73c6fd615560a96b5_63c6f3ea94d66b7dc5c199ec_63be46e3508ab6f2c169d78e_2ec6dbebf77fe703dc92d325b6d7b461.png', 'https://media-dev.exploro.com/inflight-media/nicaragua-hero.mp4', ARRAY[''], 2);


INSERT INTO country (name, slug, description_long, description_short, image_link, thumbnail_link, special_offer_image_link, video_link, gallery, featured_country) VALUES ('Nigeria', 'nigeria', 'Nigeria is one of the most impressive countries on the African continent. Many people often refer to the country as the "Giant of Africa." This nickname primarily comes from four reasons; the vastness of its land, the diversity of its peoples and languages, its large population, and the oil and other precious natural resources found on the endless expanse of land. Nigeria is a collection of distinctive regions. Travelers can discover natural environments ranging from deserts, plains, swamps, tall mountain ranges, and dense wet jungles. One of the largest river systems in the world is in Nigeria, and the third-largest delta on Earth, the Niger Delta. The majority of the country consists of massive plains and savannas. These tropical grasslands spread out far as the eye can see, occasionally giving rise to trees and shrubs here and there. The southwestern plains of the country are home to the Yoruba people, who have lived there for thousands of years. There are approximately 250 languages spoken in Nigeria and possibly up to 400!', '', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4bb8928000cf3b910a5_nigeria-banner.jpeg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4bb8928002b01b910a6_nigeria-banner.jpeg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4b73c6fd615560a96b5_63c6f3ea94d66b7dc5c199ec_63be46e3508ab6f2c169d78e_2ec6dbebf77fe703dc92d325b6d7b461.png', '', ARRAY[''], 2);


INSERT INTO country (name, slug, description_long, description_short, image_link, thumbnail_link, special_offer_image_link, video_link, gallery, featured_country, continent) VALUES ('Philippines', 'philippines', 'The Philippines is known for its many beautiful beaches, picturesque landscapes, delicious fruit trees. The country was named after King Philip II of Spain. The Philippines is made up of 7,641 islands scattered throughout the South Pacific, which makes it one of the largest archipelagos in the world. The many islands are organized under three broad geographical divisions: Luzon, Visayas, and Mindanao. The entire country covers an area of 300,000 square kilometers (120,000 sq miles) and has a population of around 109 million as of 2020. The Philippines is a multinational state, with diverse ethnicities and cultures spread out throughout its islands. Two of the more popular tourist destinations are Manila, which is the nation’s capital, and Quezon City, the country’s largest urban area.', '', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4bccaee12e946870cb2_banner_48.jpeg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4bccaee12e55b870cb1_banner_48.jpeg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4b73c6fd615560a96b5_63c6f3ea94d66b7dc5c199ec_63be46e3508ab6f2c169d78e_2ec6dbebf77fe703dc92d325b6d7b461.png', '', ARRAY[''], 2, 5);


INSERT INTO country (name, slug, description_long, description_short, image_link, thumbnail_link, special_offer_image_link, video_link, gallery, featured_country, continent) VALUES ('Qatar', 'qatar', 'Qatar is a magical, sun-kissed desert oasis! From golden sand dunes to glistening skyscrapers, the country offers something for everyone. Rich in culture and history, travelers can explore iconic monuments like the Al Zubarah Fort or take in views of the unique landscape at Katara Beach. With endless activities and attractions across the country, Qatar is an unforgettable destination.', 'Qatar is a land of adventure, culture and excitement - come explore it today!', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63d051657ebdeb2c8429f2ed_QatariStock-186227680.jpg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63d0510d7ebdebe64529e623_QatariStock-1136982068.jpg', '', '', ARRAY[''], 2, 2);


INSERT INTO country (name, slug, description_long, description_short, image_link, thumbnail_link, special_offer_image_link, video_link, gallery, featured_country) VALUES ('Rwanda', 'rwanda', 'Rwanda is home to the Virunga Mountains range, located in the northwest part of Rwanda. Although not as impressive as Killamanjaro, Rwanda is home to Karisimbi, a towering mountain that reaches nearly 15,000 feet. Uganda borders the landlocked country to the north, Burundi to the south, Tanzania to the east, and Democratic Republic of the Congo to the west. The country is known as the “land of a thousand hills” because Rwanda’s landscape is mostly hilly and mountainous. Two major African rivers flow through Rwanda, the Nile and the Congo. Lake Kivu is Africa’s sixth-largest lake, and it separates Rwanda from the Democratic Republic of Congo to the west. The lake reaches an impressive depth. It plunges 722 feet (220 meters) below the surface at its deepest point. The lake is full of fish and other wildlife, and many people live on the shores of Lake Kivu to fish its waters. Although one of Africa’s smallest countries, Rwanda has some of the highest population density on the continent, with approximately a thousand people per square mile. The main two ethnic populations in the country are the Hutu and the Tutsi and Rwanda is today a great place for both ethnicities and foreign travelers.', '', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4bc23ecaa26e5a391b0_rwanda-banner.jpeg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4bc23ecaa220da391af_rwanda-banner.jpeg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4b73c6fd615560a96b5_63c6f3ea94d66b7dc5c199ec_63be46e3508ab6f2c169d78e_2ec6dbebf77fe703dc92d325b6d7b461.png', '', ARRAY[''], 2);


INSERT INTO country (name, slug, description_long, description_short, image_link, thumbnail_link, special_offer_image_link, video_link, gallery, featured_country) VALUES ('Senegal', 'senegal', 'Senegal is a French-speaking country located in western Africa. It sits on the Atlantic Ocean, and much of the country enjoy the coast. Senegal has an incredibly ancient history with the earliest known human settlement dating back to over 350,000 years ago! The Stone Circles of Senegambia date back as far as the 3rd century BC and are now considered a World Heritage Site. Senegal is a peaceful place to live and is often praised for incorporating all its ethnic and religious groups into a peaceful society. The largest ethnic group in Senegal is Wolof, forming 43% of the population. The Fula and Toucouler are the second largest ethnic group forming 24% of the population. The Bassari and Bedick make up 9% of the population. Senegal is officially secular but is mostly a Muslim country (92% of the population). Senegal is vibrant and welcoming, where rich traditions and natural beauty combine to make a great place to visit, including the sandy beaches and textured landscapes.', '', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4bc7d5d84e7b538228b_senegal-banner.jpeg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4bc7d5d846ddd38228a_senegal-banner.jpeg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4b73c6fd615560a96b5_63c6f3ea94d66b7dc5c199ec_63be46e3508ab6f2c169d78e_2ec6dbebf77fe703dc92d325b6d7b461.png', '', ARRAY[''], 2);


INSERT INTO country (name, slug, description_long, description_short, image_link, thumbnail_link, special_offer_image_link, video_link, gallery, featured_country, continent) VALUES ('Seychelles', 'seychelles', 'Seychelles is comprised of 115 islands in the Indian Ocean. The islands lie off the coast of eastern Africa, just northeast of Madagascar. Few of these islands are inhabited, but all hold a unique beauty. The majority of Seychelles’ population lives on the granite islands, home to the bulk of the country’s resorts. Seychelles is the smallest country in Africa, both in terms of population and landmass. Hundreds of years ago, Maldivian and Arab traders were the first to visit the uninhabited islands. Like many African nations, ownership was contested between the British and the French for many years and Seychelles achieved independence in 1976. Free elections began in 1993. Seychelles is a beautiful destination and tourists enjoy pristine beaches and hot, humid weather, with average temperatures at 84°F (29°C) year-round. The citizens primarily speak one of three languages, Seychellois Creole, English, and French.', '', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4bc1bf36a6c533dbf01_seychelles-banner.jpeg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4bc1bf36a84283dbf02_seychelles-banner.jpeg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4b73c6fd615560a96b5_63c6f3ea94d66b7dc5c199ec_63be46e3508ab6f2c169d78e_2ec6dbebf77fe703dc92d325b6d7b461.png', '', ARRAY[''], 2, 3);


INSERT INTO country (name, slug, description_long, description_short, image_link, thumbnail_link, special_offer_image_link, video_link, gallery, featured_country, continent) VALUES ('Sierra Leone', 'sierra-leone', 'Sierra Leone was founded as a haven for formerly enslaved people, and is located on the West Coast of Africa. Sierra Leone is bursting with scenic beauty and has many natural resources. It has incredible beaches, some of the best in the world, a rich, proud heritage, and truly stunning scenery. And with all of that, travelers can also expect a welcoming, friendly populace, most of whom will help foreigners in any way. Sierra Leone has made much progress on building roads, dams, providing power, and other public services. Additionally, the government and private sector efforts have ramped up, and Sierra Leone is growing into a great tourist destination.', '', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4bc48c76d4aaeac890c_sierra-leone-banner.jpeg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4bc48c76d3d34ac890b_sierra-leone-banner.jpeg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4b73c6fd615560a96b5_63c6f3ea94d66b7dc5c199ec_63be46e3508ab6f2c169d78e_2ec6dbebf77fe703dc92d325b6d7b461.png', '', ARRAY[''], 2, 5);


INSERT INTO country (name, slug, description_long, description_short, image_link, thumbnail_link, special_offer_image_link, video_link, gallery, featured_country, continent) VALUES ('Singapore', 'singapore', 'Singapore is one of the wealthiest countries in all south-east Asia. It holds the unique position of being a city, a nation, and a state. The area started out as a British colonial trading post, after which it underwent several regimes before becoming independent in the latter half of the 20th century. In just three generations, Singapore managed to transform itself from a third-world country to a thriving global financial hub described as one of Asia’s economic "tigers". This meteoric rise can be attributed to its advanced technological infrastructure, availability of skilled labor, favorable immigration laws, and the efficient way in which new businesses can be set up here. The territory includes one main island, 63 satellite islands and islets, and one outlying islet. The country has also managed to increase its territory by 25% due to extensive land reclamation projects. It is one of the safest nations in the world.', '', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4bcf78793f4d1229410_banner_46.jpeg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4bcf78793543d22940f_banner_46.jpeg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4b73c6fd615560a96b5_63c6f3ea94d66b7dc5c199ec_63be46e3508ab6f2c169d78e_2ec6dbebf77fe703dc92d325b6d7b461.png', '', ARRAY[''], 2, 5);


INSERT INTO country (name, slug, description_long, description_short, image_link, thumbnail_link, special_offer_image_link, video_link, gallery, featured_country) VALUES ('South Sudan', 'south-sudan', 'South Sudan is a lush tropical paradise that enjoys frequent rainfall and thick jungles. Over 12 and a half million people call this country home, with&nbsp;more than 60 indigenous ethnicities. The Dinka comprise 40% of the population. There are some stunning, unique cultures in South Sudan which are maintained by the pleasant features of the countryside. To enjoy the amazing aspects of South Sudan, it is necessary to embrace the remoteness and travel a few hours outside the main cities. If traveling outside the city, it is important to hire knowledgeable tour leaders for the trip.', '', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4bc3c6fd6efb10a9783_south-sudan-banner.jpeg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4bc3c6fd6079e0a9782_south-sudan-banner.jpeg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4b73c6fd615560a96b5_63c6f3ea94d66b7dc5c199ec_63be46e3508ab6f2c169d78e_2ec6dbebf77fe703dc92d325b6d7b461.png', '', ARRAY[''], 2);


INSERT INTO country (name, slug, description_long, description_short, image_link, thumbnail_link, special_offer_image_link, video_link, gallery, featured_country, continent) VALUES ('Spain', 'spain', 'Spain is considered an exotic European country due to its friendly inhabitants, relaxed lifestyle, world-famous folklore and festivities, cuisine, and an exciting nightlife. A few places to visit in Spain include Spain’s thriving capital Madrid, the famous "Running of the Bulls" at Pamplona, the beautiful coastal city of Barcelona, major Andalusian cities with Islamic architecture, like Seville, Granada, and Córdoba, the Way of St. James and the idyllic Balearic and Canary Islands. Spain is on the beautiful Mediterranean coast and is full of rich history and culture, stunning landscapes, and friendly people.', '', '', '', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4b73c6fd615560a96b5_63c6f3ea94d66b7dc5c199ec_63be46e3508ab6f2c169d78e_2ec6dbebf77fe703dc92d325b6d7b461.png', '', ARRAY[''], 2, 3);


INSERT INTO country (name, slug, description_long, description_short, image_link, thumbnail_link, special_offer_image_link, video_link, gallery, featured_country, continent) VALUES ('St Maarten', 'st-maarten', 'St. Maarten&nbsp;is the smallest land mass inhabited in the world, shared by two countries: France and the Netherlands. St. Maarten occupies the northern 60% of the island and is an overseas collectivity of France. The Dutch side is the southern part of the island, and has been an independent country since October 2010, still part of the Netherlands but not considered European territory. St. Maarten has natural beauty in the form of breathtaking shorelines with beautiful beaches, coves, bluffs overlooking harbors, and lagoons with the bluest waters. You can find luxury hotels, elegant villas, fantastic shopping opportunities, over 300 restaurants, diverse cultures, trendy art scenes, and exciting and vibrant nightlife. All are ready to be soaked in and explored.', '', '', '', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4b73c6fd615560a96b5_63c6f3ea94d66b7dc5c199ec_63be46e3508ab6f2c169d78e_2ec6dbebf77fe703dc92d325b6d7b461.png', 'https://media-dev.exploro.com/inflight-media/st.-maarten.mp4', ARRAY[''], 2, 3);


INSERT INTO country (name, slug, description_long, description_short, image_link, thumbnail_link, special_offer_image_link, video_link, gallery, featured_country) VALUES ('Sudan', 'sudan', 'The large and mostly desert country of Sudan sits on Egypt’s southern border. The life-giving Nile river runs through the country, and the Red Sea connects to its eastern coast. The area around the River Nile was once known as Nubia, one of the world’s earliest civilizations. Nubia challenged Egypt to its North and remained an independent state for thousands of years. In fact, even the Romans could not conquer the Nubians. This warlike past lives on in modern-day Sudan, and the area had seen 40 years of civil wars before South Sudan claimed independence. If you are able to visit, be aware that “travel to the western part of the country especially Darfur, and to the borders with Southern Sudan and Eritrea is dangerous and strongly discouraged”. The silver lining is that tourist attractions will have few lines, and there is much to see in this incredibly diverse country. Sudan has nearly 600 ethnic groups and is home to ancient kingdoms.', '', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4bd0bec5c254fb75d34_sudan-banner.jpeg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4bd0bec5c254fb75d34_sudan-banner.jpeg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4b73c6fd615560a96b5_63c6f3ea94d66b7dc5c199ec_63be46e3508ab6f2c169d78e_2ec6dbebf77fe703dc92d325b6d7b461.png', '', ARRAY[''], 2);


INSERT INTO country (name, slug, description_long, description_short, image_link, thumbnail_link, special_offer_image_link, video_link, gallery, featured_country, continent) VALUES ('Sweden', 'sweden', 'Sweden is an environmentally stunning Scandinavian nation with thousands of beautiful coastal islands, gorgeous inland lakes, vast boreal forests, and glaciated mountains. Its principal cities, eastern capital Stockholm and southwestern Gothenburg and Malmö, are all coastal and full of unique activities and dining spots. Stockholm, one of its smaller cities, is built on 14 islands and has more than 50 old-time bridges. The medieval old town, Gamla Stan, has astonishing royal palaces and museums like the open-air Skansen.', '', '', '', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4b73c6fd615560a96b5_63c6f3ea94d66b7dc5c199ec_63be46e3508ab6f2c169d78e_2ec6dbebf77fe703dc92d325b6d7b461.png', '', ARRAY[''], 2, 3);


INSERT INTO country (name, slug, description_long, description_short, image_link, thumbnail_link, special_offer_image_link, video_link, gallery, featured_country, continent) VALUES ('Taiwan', 'taiwan', 'The Republic of China (ROC) was a country in East Asia based in mainland China from 1912 to 1949. The Republic declared its independence on the first day of January 1912, after the Xinhai Revolution, where they overthrew the last imperial dynasty of China, the Qing dynasty. The country maintained independence until the middle of the century. After the Chinese Civil War, its government was relocated to Taiwan. Before the breaking up of the country, it had attained a population of 541 million by 1949, which made it the world’s most populated country at that time. It covered a total area of 11.4 million square kilometers (4.4 million square miles).', '', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4bdd690b8489c373ba8_banner_45.jpeg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4bdd690b8b403373ba7_banner_45.jpeg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4b73c6fd615560a96b5_63c6f3ea94d66b7dc5c199ec_63be46e3508ab6f2c169d78e_2ec6dbebf77fe703dc92d325b6d7b461.png', '', ARRAY[''], 2, 5);


INSERT INTO country (name, slug, description_long, description_short, image_link, thumbnail_link, special_offer_image_link, video_link, gallery, featured_country) VALUES ('Tanzania', 'tanzania', 'Tanzania is home to Olduvai Gorge, in the northern part of the country, and known as “The Cradle of Civilization," with some of the oldest settlements in the world. Tanzania today is home to about 120 African tribal groups. In 1964, Tanzania was formed when Tanganyika and Zanzibar became independent countries and merged to form the nation of Tanzania, which is the largest country in East Africa and includes the islands of Zanzibar, Pemba, and Mafia. The country shares borders with the Indian Ocean and eight other countries. It is the world’s largest producer of cloves, a spice full of antioxidants. Once an active volcano, the iconic Mount Kilimanjaro sees snow on its peak year-round. Tanzania is bordered by three of the continent’s largest lakes: Lake Victoria (the world’s second-largest freshwater lake) to the north, Lake Tanganyika to the west, and Lake Nyasa to the southwest and is the highest point in Africa. About 90 percent of the country’s population live in rural areas and live off what they can grow on the land. Many ancient traditions have survived this ethnic blending and arranged marriages are still customary for many Tanzanian families. Many of the most well-known African mammal species such as wildebeest, zebra, giraffe, elephant, rhino, lion, and leopard are native to Tanzania.', '', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4bdc9d419e1af4f49c1_tanzania-banner.jpeg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4bdc9d419e1af4f49c1_tanzania-banner.jpeg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4b73c6fd615560a96b5_63c6f3ea94d66b7dc5c199ec_63be46e3508ab6f2c169d78e_2ec6dbebf77fe703dc92d325b6d7b461.png', '', ARRAY[''], 2);


INSERT INTO country (name, slug, description_long, description_short, image_link, thumbnail_link, special_offer_image_link, video_link, gallery, featured_country, continent) VALUES ('Turks and Caicos Islands', 'turks-and-caicos-islands', 'Experience the beauty of Providenciales, known as ''Provo'' to locals, a tropical island in the Turks & Caicos with dazzling beaches & a vibrant culture.', 'Experience the beauty of Providenciales, known as ''Provo'' to locals, a tropical island in the Turks & Caicos with dazzling beaches & a vibrant culture.', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c9979d346a6e6740c6bfc9_download.jpg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c9979d346a6e6740c6bfc9_download.jpg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c9971a14afcf29e6e66a0b_63be46e3508ab6f2c169d78e_2ec6dbebf77fe703dc92d325b6d7b461.png', '', ARRAY[''], 2, 6);


INSERT INTO country (name, slug, description_long, description_short, image_link, thumbnail_link, special_offer_image_link, video_link, gallery, featured_country, continent) VALUES ('U.S. Virgin Islands', 'u-s-virgin-islands', 'These islands are unincorporated organized territories of the United States of America and are close to Puerto Rico. This tropical paradise has fantastic beaches and bright blue waters surrounding the islands. Complete with relatively low humidity, a slight breeze, and consistent temperature all year along, it is a great place to spend your vacations any time of year.', '', '', '', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4b73c6fd615560a96b5_63c6f3ea94d66b7dc5c199ec_63be46e3508ab6f2c169d78e_2ec6dbebf77fe703dc92d325b6d7b461.png', 'https://media-dev.exploro.com/inflight-media/us-virgin-islands-hero.mp4', ARRAY[''], 2, 4);


INSERT INTO country (name, slug, description_long, description_short, image_link, thumbnail_link, special_offer_image_link, video_link, gallery, featured_country) VALUES ('Uganda', 'uganda', 'Uganda is named for the Buganda kingdom, which encompasses a large part of the south, including Kampala. Football, known in the west as soccer, is the national sport in Uganda and is played by many. Citizens come from all over to support their favorite teams at modern arenas. The beautiful and busy capital city, Kampala, boasts dozens of small parks, public gardens, and a scenic promenade resting peacefully along the shore of Lake Victoria, Africa’s largest freshwater lake. The Swahili language unites the country with its East African neighbors Kenya and Tanzania and is the primary spoken language. Photo safaris in the national parks and game reserves are very popular and other places to visit are the Mountain Gorillas found in Bwindi Impenetrable National Park (BINP) and Mgahinga Gorilla National Park (MGNP). Uganda has some of the oldest cultural kingdoms in Africa.', '', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4bdc9d4191dd34f49c3_uganda-banner.jpeg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4bdc9d4191dd34f49c3_uganda-banner.jpeg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4b73c6fd615560a96b5_63c6f3ea94d66b7dc5c199ec_63be46e3508ab6f2c169d78e_2ec6dbebf77fe703dc92d325b6d7b461.png', '', ARRAY[''], 2);


INSERT INTO country (name, slug, description_long, description_short, image_link, thumbnail_link, special_offer_image_link, video_link, gallery, featured_country) VALUES ('Zambia', 'zambia', 'Zambia is an incredible country, home to many natural wonders and outdoor activities. Zambia is home to Victoria Falls, one of the World’s Seven Natural Wonders and a UNESCO World Heritage Site. The falls are locally known as Mosi-oa-Tunya (meaning "The Smoke That Thunders"). It is truly one of the most impressive sights in the world. Although the falls do not hold the highest, most expansive, or greatest volume of water, they do have the largest sheet of water in the world, and are a sight you do not want to miss. The country found its independence in 1964 and in 1991, Zambia became a multi-party democracy. &nbsp;Over 17 million people call this landlocked country home and there are multiple ethnic groups. The diverse ethnic groups have lived side-by-side for many generations, and their languages have a commonality. There are many festivals throughout Zambia, and parks and safari areas which enjoy stunning wildlife, unspoiled landscapes and very friendly people.', '', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4becaee120f87870d53_zambia-banner.jpeg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4becaee12ba9b870d54_zambia-banner.jpeg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4b73c6fd615560a96b5_63c6f3ea94d66b7dc5c199ec_63be46e3508ab6f2c169d78e_2ec6dbebf77fe703dc92d325b6d7b461.png', '', ARRAY[''], 2);


INSERT INTO country (name, slug, description_long, description_short, image_link, thumbnail_link, special_offer_image_link, video_link, gallery, featured_country) VALUES ('Zimbabwe', 'zimbabwe', 'Zimbabwe is a beautiful African country located between the Zambezi and Limpopo Rivers. It is a landlocked country in the south of Africa and is incredibly diverse with 16 official languages! Zimbabwe first celebrated its independence on the 18th of April in 1980. Every year citizens remember this eventful time with celebrations, where everyone sings the national anthem, doves are released, and fighter jets fly over. Zimbabwe’s traditional arts include pottery, basketry, textiles, jewelry, and different carvings. For celebrations, a popular activity is roasting a goat or cow with many families. Known for its warm and welcoming people it is the perfect holiday destination for lovers of the great outdoors. From the bustling wildlife in the country’s grasslands to ancient sites, you can find the best outdoor experiences around in Zimbabwe.', '', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4becae3db4e9bd2623a_zimbabwe-banner.jpeg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4becae3dbc391d26239_zimbabwe-banner.jpeg', 'https://uploads-ssl.webflow.com/63be358a2ba7e25fed479661/63c8c4b73c6fd615560a96b5_63c6f3ea94d66b7dc5c199ec_63be46e3508ab6f2c169d78e_2ec6dbebf77fe703dc92d325b6d7b461.png', '', ARRAY[''], 2);

